### ISSUE TITLE
建議 metadata 加上 namespace

### ISSUE THREAD

**Issue by life1347** [morningstar3718/k8s-homework#1]
在 multi-tenancy 的環境下，為 object 設定適當的 namespace 有助於管理資源
cfgmap & secret 都有類似小問題

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: password
  namespace: default
data:
  password: cfgmap-password
```

第一個看到有寫文件說明的! Good job!
